### ISSUE TITLE
Spajanje na bazu

### ISSUE THREAD

**Issue by mateod747** [jelenatufekovic/Praksa2021-g01#18]
U repozitorijima:

using System.Data.SqlClient;
using Results.Common.Utils;

static string con = ConnectionString.GetDefaultConnectionString();

static SqlConnection conn = new SqlConnection(con);

U metodama otvaranje i zatvaranje konekcije te pisanje i izvršavanje sql komandi.

**Comment by avukalov** [comment]
Napisao sam static Classu ConnectionString gdje samo trebate pozvat metodu GetDefaultConnectioString

Dodatno: 
Procitajte na slacku o konekciji, kako dodati svoju lokalnu bez narusavanja azure stringa

To mogu na skypu pokazat
